/*
 * This file is generated by jOOQ.
 */
package com.chatapp.jooq;


import com.chatapp.jooq.tables.ChatRoomUsers;
import com.chatapp.jooq.tables.ChatRooms;
import com.chatapp.jooq.tables.Messages;
import com.chatapp.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chat_room_users</code>.
     */
    public final ChatRoomUsers CHAT_ROOM_USERS = ChatRoomUsers.CHAT_ROOM_USERS;

    /**
     * The table <code>public.chat_rooms</code>.
     */
    public final ChatRooms CHAT_ROOMS = ChatRooms.CHAT_ROOMS;

    /**
     * The table <code>public.messages</code>.
     */
    public final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChatRoomUsers.CHAT_ROOM_USERS,
            ChatRooms.CHAT_ROOMS,
            Messages.MESSAGES,
            Users.USERS
        );
    }
}
