/*
 * This file is generated by jOOQ.
 */
package com.chatapp.jooq;


import com.chatapp.jooq.tables.ChatRoomUsers;
import com.chatapp.jooq.tables.ChatRooms;
import com.chatapp.jooq.tables.Messages;
import com.chatapp.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat_room_users</code>.
     */
    public static final ChatRoomUsers CHAT_ROOM_USERS = ChatRoomUsers.CHAT_ROOM_USERS;

    /**
     * The table <code>public.chat_rooms</code>.
     */
    public static final ChatRooms CHAT_ROOMS = ChatRooms.CHAT_ROOMS;

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
