/*
 * This file is generated by jOOQ.
 */
package com.chatapp.jooq.tables.records;


import com.chatapp.jooq.tables.ChatRoomUsers;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRoomUsersRecord extends UpdatableRecordImpl<ChatRoomUsersRecord> implements Record4<Integer, Integer, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_room_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat_room_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.chat_room_users.chat_room_id</code>.
     */
    public void setChatRoomId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat_room_users.chat_room_id</code>.
     */
    public Integer getChatRoomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.chat_room_users.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chat_room_users.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.chat_room_users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chat_room_users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, UUID, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, UUID, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChatRoomUsers.CHAT_ROOM_USERS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ChatRoomUsers.CHAT_ROOM_USERS.CHAT_ROOM_ID;
    }

    @Override
    public Field<UUID> field3() {
        return ChatRoomUsers.CHAT_ROOM_USERS.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ChatRoomUsers.CHAT_ROOM_USERS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getChatRoomId();
    }

    @Override
    public UUID component3() {
        return getUserId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getChatRoomId();
    }

    @Override
    public UUID value3() {
        return getUserId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public ChatRoomUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChatRoomUsersRecord value2(Integer value) {
        setChatRoomId(value);
        return this;
    }

    @Override
    public ChatRoomUsersRecord value3(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public ChatRoomUsersRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ChatRoomUsersRecord values(Integer value1, Integer value2, UUID value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRoomUsersRecord
     */
    public ChatRoomUsersRecord() {
        super(ChatRoomUsers.CHAT_ROOM_USERS);
    }

    /**
     * Create a detached, initialised ChatRoomUsersRecord
     */
    public ChatRoomUsersRecord(Integer id, Integer chatRoomId, UUID userId, LocalDateTime createdAt) {
        super(ChatRoomUsers.CHAT_ROOM_USERS);

        setId(id);
        setChatRoomId(chatRoomId);
        setUserId(userId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
